--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/sky-min/InventoryLib
branches:
- master
- pm5
projects:
  InventoryLib:
    path: ""
    model: virion
    type: library
    libs:
      - src: sky-min/EventAttribute/EventAttribute
        version: ^2.0.0
...
